name: Development CI

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'directory_analyzer.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  quick-test:
    # Cost-optimized: Only test on Ubuntu with latest Python for development branches
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    # Cache pip dependencies to optimize build times
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-3.13-dev-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.13-
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install minimal development dependencies
        pip install pytest flake8
    
    - name: Quick lint check
      run: |
        # Check for critical syntax errors only
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Run core tests
      run: |
        python -m pytest tests/ -v --tb=short
    
    - name: Basic functionality test
      run: |
        python directory_analyzer.py --help
        python directory_analyzer.py --version
